name: run-py-script

on: 
  push:
    branches:
      - master

jobs:
  buidl:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code of this repo
        uses: actions/checkout@v2
        with:
            path: main

      - name: Checkout code of code repo
        uses: actions/checkout@v2
        with:
            repository: mattedamo/thesis-code-repo-python
            token: ${{secrets.API_TOKEN_GITHUB}}
            path: code-repo
      - run: ls
      - run: cp code-repo/ile.yaml main/
      - run: cd main
      - run: ls
      - run: rm ile.yaml
      - run: ls 
