name: Update-infrastructure-backend

on: 
  workflow_dispatch:
    inputs:
      sha-tag:
        description: 'sha tag for new image'     
        required: true
      code-branch:
        description: 'branch of code repository'
        required: true
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "sha: ${{ github.event.inputs.sha-tag }}"
          echo "Log level: ${{ github.event.inputs.code-branch}}"
          
          
