name: run-py-script

on: 
  push:
    branches:
      - master

jobs:
  buidl:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code of this repo
        uses: actions/checkout@v2
        with:
            path: main

      - name: Checkout code of code repo
        uses: actions/checkout@v2
        with:
            repository: mattedamo/thesis-code-repo-python
            token: ${{secrets.API_TOKEN_GITHUB}}
            path: code-repo
      - run: ls
      - run: cp code-repo/file.yaml main/file.yaml
      - run: ls main/
      - run: rm -f main/file.yaml
      - run: ls main/
